on: [push]

name: deploy-shiny-app

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    container: vinnykos/shinyauth
    steps:
      - uses: actions/checkout@v2
      - name: Run docker container image
        run: |
          pwd
