on: [push]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    container: vinnykos/shinyauth
    steps:
      - name: Run docker container image
        run: |
          docker run -d --name meu-shiny -p 3838:3838 vinnykos/shinyauth
