on: [push]

name: deploy-shiny-app

jobs:
  deploy-shiny:
    runs-on: ubuntu-20.04
    container: 
      image: vinnykos/shinyauth
      options: --rm
      ports:
        - 3838:3838
      volumes: 
        - ${{ github.workspace }}/bayesian_abtest_rshiny/app/:/srv/shiny-server/test_app
        - ${{ github.workspace }}/log/shiny-server/:/var/log/shiny-server/ vinnykos/shinyauth
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get folder
        run: |
          pwd
          sudo apt-get install tree
          tree
          
      - name: run app
        run: | 
          R -e "shiny::runApp('app/app.R', port = 3838, host = '0.0.0.0', launch.browser = TRUE)"
