on: [push]

name: deploy-shiny-app

jobs:
  deploy-shiny:
    runs-on: ubuntu-20.04
    container: 
      image: vinnykos/shinyauth
      options: -rm -p 3838:3838 -v ${{ github.workspace }}/bayesian_abtest_rshiny/app/:/srv/shiny-server/test_app -v ${{ github.workspace }}/log/shiny-server/:/var/log/shiny-server/ vinnykos/shinyauth
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run docker container image
        run: | 
          ls -la
      - name: Get folder
        run: |
          pwd
