on: [push]

name: deploy-shiny-app

jobs:
  deploy-shiny:
    runs-on: ubuntu-20.04
    container: 
      image: vinnykos/shinyauth
      options: --rm
      ports:
        - 3838:3838
      volumes: 
        - ${{ github.workspace }}/bayesian_abtest_rshiny/app/:/srv/shiny-server/test_app
        - ${{ github.workspace }}/log/shiny-server/:/var/log/shiny-server/ vinnykos/shinyauth
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get folder
        run: |
          pwd
          sudo apt-get install tree
          tree
          
          
      - name: Install dependencies
        run: |
          # Install required tools
          sudo apt-get update
          sudo apt-get install -y curl

      - name: Test Shiny App
        run: |
          R -e "shiny::runApp('app/app.R', port = 3838, host = '0.0.0.0', launch.browser = FALSE)" &

      - name: Wait for Shiny App to start
        run: sleep 10
        
      - name: Test Shiny App
        run: |
          # Make an HTTP request to the running Shiny app
          response=$(curl -sL -w "%{http_code}" http://localhost:3838/ -o /dev/null)
          # Check the HTTP response code
          if [ "$response" -eq 200 ]; then
            echo "Shiny app is running."
          else
            echo "Shiny app is not running."
          fi

